travis:
  secure:
    BINSTAR_TOKEN: f0SXUBSrTxLFASUWbxqHlHFkBgcr9b5IJ/0HfJ0kExBbUG8hbFq+J8ZVjNwh8g/8kAxWTIeixbkjfRnvKSFEuetTc+ba7A1NxDFER9MXjxFMvlqnpcE36ifHsQ2f1j/j7YZEXVyeXBaIioonFwxrL4Obv3+COTDtCRC42zutUrNprpwS/SFqHEXuC4cGBRirjRtl59HmkzpzxXc9VYaxvf6q2OqKo0Ek5nkrLaEEqE967WYY2Ddna2PXMwzH6QhZjcHgVy3oMoehzwdMljX3JCNHHluKJaAKbf/G6B3QbMoj6bb7ErCCJhNUjhclVg1HFUHjOYi14vwPOri+xL4OilTWrseXUqtBKz2YVy8F82DJdt7RJm6oxQ1BVUiSc34ftPpIBTKUUxPaHzvu8GHrNqb4afPL7Elo3rECub8iRgd5f+3Wt/xmK9KPaYfswcz2P0t4d6v2nX333sKwaxqEtUOQBcWMzjx6pdQo3TvJxLDwXHbRZ0E5WZmvcjq3loTyN4b/b2hxGFS61jWRpTYGlABsEcLRGdq8tTCLj2PtVAfgywtsoMsUNQSQHqLmZR0F6kgyZUPpLZXKVTJT468jTeaIS2z95L8tBUgxobcbQktxEOBUHj8x+7BlicmoNMAAaO01OfN+1OXwlnTnBJ31qyusXGiUVmS3O4QU5wTSwfM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
